# Generated by Django 2.2.28 on 2024-03-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240312_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='app.Activity'),
        ),
    ]
