# Generated by Django 4.2.11 on 2024-03-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_place_img_ref_place_slug_alter_event_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
