# Generated by Django 2.2.28 on 2024-03-19 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240315_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Default Event Name', max_length=255),
        ),
    ]
