# Generated by Django 2.2.28 on 2024-03-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240319_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img_ref',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
