# Generated by Django 2.2.28 on 2024-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240322_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='img_ref',
            field=models.CharField(default='', max_length=100),
        ),
    ]
